#!/bin/bash


set -e

# Check for username argument
if [ -z "$1" ]; then
	echo "Usage: $0 <username>"
	exit 1
fi

USERNAME="$1"

mkdir "users/${USERNAME}"
mkdir "inbox/${USERNAME}"
mkdir "outbox/${USERNAME}"
cd "users/${USERNAME}"

# 1. Generate a 2048-bit RSA private key in PEM format
ssh-keygen -t rsa -b 2048 -m PEM -f "${USERNAME}.pem" -N ""

# 2. Export the public key in PEM format (required by ActivityPub)
ssh-keygen -f "${USERNAME}.pem" -e -m PEM > "${USERNAME}_pub.pem"

cp "${USERNAME}.pem" "${USERNAME}.ssh"
mv "${USERNAME}.pem.pub" "${USERNAME}_pub.ssh" # created by first command, SSH format, useless to us


